server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8

    
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/ttf?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    url: jdbc:mysql://122.51.73.55:3306/onepoint?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&allowMultiQueries=true
    username: fnst
    password: VjD1bw1t&w96RM#!
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1 FROM DUAL
    time-between-eviction-runs-millis: 300000
    min-evictable-idle-time-millis: 1800000
#    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 200
      minimum-idle: 10
  
  jackson:
    time-zone: GMT+8
        
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
      
   
  thymeleaf:
    prefix: classpath:/templates
      
mybatis:
  type-aliases-package: com.fujitsu.ttf.crm.entity
#  指定mapper 的配置文件位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  
 
logging:
 level:
  com:
   fujitsu:
    ttf:
     yd:
      mapper: debug